title: Hacker Theme
author: Your Name
description: A Jekyll site with a hacker theme
url: https://yourusername.github.io
baseurl: ""

theme: jekyll-theme-hacker

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author_profile: true
      comments: true
      share: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    line_numbers: true
    span:
      line_numbers: 'line-%N'

permalink: pretty
